from src.constants import *
import os


ROOT_DIR = ROOT_DIR_KEY
DATASET_PATH = os.path.join(ROOT_DIR,ARTIFACT_DIR_KEY,DATA_FOLDER,DATA_YAML_FILE)

MODEL_PATH = os.path.join(ROOT_DIR,ARTIFACT_DIR_KEY,MODEL_FOLDER,CURRENT_MODEL)

# STUB_PATH = os.path.join(ROOT_DIR,ARTIFACT_DIR_KEY,STUBS_FOLDER,STUB_FILE)
STUB_PATH = os.path.join(ROOT_DIR,ARTIFACT_DIR_KEY,STUBS_FOLDER)
VIDEO_INPUT_PATH  = os.path.join(ROOT_DIR,ARTIFACT_DIR_KEY,INPUT_FOLDER,VIDEO_FOLDER,VIDEO_FILE)

IMAGE_INPUT_PATH  = os.path.join(ROOT_DIR,ARTIFACT_DIR_KEY,INPUT_FOLDER,IMAGE_FOLDER,IMAGE_FILE)

IMAGE_INPUT_MULTIPLE_FOLDER = os.path.join(ROOT_DIR,ARTIFACT_DIR_KEY,INPUT_FOLDER,IMAGE_FOLDER)


    
